type: docker
kind: pipeline
name: default

steps:
  - name: Build private image
    image: plugins/docker
    settings:
      repo: git.maki-it.corp/kim/lexoffice-invoice-upload
      registry: git.maki-it.corp
      username: 
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags:
        - develop
    depends_on:
      - clone
    
  - name: Test
    image: git.maki-it.corp/kim/lexoffice-invoice-upload:develop
    pull: always
    environment:
      TESTCONFIG:
        from_secret: testconfig.ini
      FILEPATH: /app/config/test.ini
      DEBUG: True
      CRON: '*/1 * * * *'
    commands:
      - python3 /app/main.py -h
      - python3 /app/main.py --generate --configfile $FILEPATH
      - echo "$TESTCONFIG" > $FILEPATH
      - echo "python3 /app/main.py --configfile $FILEPATH --continuous --cron '$CRON' --run-once"
      - /app/docker/entrypoint.sh python3 /app/main.py --configfile $FILEPATH --continuous --cron "$CRON" --run-once 2>&1
    depends_on:
      - Build private image    

  - name: Recreate live testing
    image: alpine/curl:latest
    commands:
      - "curl -X POST https://docker.maki-it.corp/api/stacks/webhooks/534764f3-6427-4321-82e0-ebfefd4b2e3b"
    depends_on:
      - Test

  - name: push to dockerhub
    image: plugins/docker
    settings:
      repo: makiit/lexoffice-invoice-upload
      username: 
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      registry: docker.io
      tags:
        - latest
    depends_on:
      - Test
    when:
      event:
      - pull_request
      - tag
      - custom

  - name: push to github cr
    image: plugins/docker
    settings:
      repo: ghcr.io/maki-it/lexoffice-invoice-upload
      username: 
        from_secret: github_user
      password:
        from_secret: github_token
      registry: ghcr.io
      tags:
        - latest
    depends_on:
      - Test
    when:
      event:
      - pull_request
      - tag
      - custom