type: docker
kind: pipeline
name: default

steps:
  - name: build private image
    image: plugins/docker
    settings:
      repo: git.maki-it.corp/kim/lexoffice-voucher-upload
      registry: git.maki-it.corp
      username: 
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags:
        - develop
    
  - name: test pycurl
    image: git.maki-it.corp/kim/lexoffice-voucher-upload:develop
    commands:
      - python3 /app/main.py --generate --config /app/config/test.ini
      - "python3 /app/main.py --config /app/config/test.ini --continuous --intervall $INTERVALL 2>&1" 

  - name: Recreate live testing
    image: alpine/curl:latest
    commands:
      - "curl -X POST https://docker.maki-it.corp/api/stacks/webhooks/534764f3-6427-4321-82e0-ebfefd4b2e3b"

  - name: build public image
    image: plugins/docker
    settings:
      repo: kimdrechsel/lexoffice-voucher-upload
      username: kimdrechsel
      password:
        from_secret: dockerhub_token
      registry: docker.io
      tags:
        - latest
      when:
        event:
        - promote
        target:
        - production