version: "3"

volumes:
  config:

services:
  app:
    image: makiit/lexoffice-invoice-upload:latest
    volumes:
      - config:/app/config
    environment:
      TZ: Europe/Berlin
      CRON: '*/5 * * * *'
    restart: unless-stopped
