name: Test

on:
  push:
    branches:
      - '**'
      - '!master'

env:
  FILEPATH: testconfig.ini
  CRON: '* * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aptitude
          sudo aptitude install -y libssl-dev libcurl4-openssl-dev libcurl4-gnutls-dev python3-dev
          pip install pycurl
          pip install -r requirements.txt

      - name: Generate config file
        run: |
          - python3 /app/main.py -h
          - python3 /app/main.py --generate --configfile ${{ env.FILEPATH }}
          - cat ${{ env.FILEPATH }}

      - name: Run app
        run: |
          - echo "${{ secrets.TEST_CONFIG }}" > ${{ env.FILEPATH }}
          - echo "python3 /app/main.py --configfile ${{ env.FILEPATH }} --continuous --cron '${{ env.CRON }}' --run-once"
          - /app/docker/entrypoint.sh python3 /app/main.py --configfile ${{ env.FILEPATH }} --continuous --cron "${{ env.CRON }}" --run-once 2>&1
